name: ci-cd
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'dbt/**/*'

env:
  AWS_REGION: ap-southeast-2
  ECR_REPO_URI: 851886554434.dkr.ecr.ap-southeast-2.amazonaws.com/databricks-platform
  AWS_ROLE_TO_ASSUME: arn:aws:iam::851886554434:role/gha-role

jobs:
  ###############################
  # Continuous Integration      #
  ###############################
  ci: 
    runs-on: ubuntu-latest
    container: 
      image: python:3.11

    steps: 
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
      
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
      
      # - name: Set up python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dbt/requirements.txt

      - name: Run dbt linting checks
        run: | 
          bash ./bin/dbt_linter.sh

  ###############################
  # Continuous Deployment       #
  ###############################
  cd:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ./dbt
        env:
          IMAGE_TAG: latest
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "Target repo: ${ECR_REPO_URI}:${IMAGE_TAG}"
          docker build -t ${ECR_REPO_URI}:${IMAGE_TAG} .
          docker push ${ECR_REPO_URI}:${IMAGE_TAG}
          echo "image=${ECR_REPO_URI}:${IMAGE_TAG}" >> $GITHUB_OUTPUT