name: ci
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  ci_dbt: 
    runs-on: ubuntu-latest
    container: 
      image: python:3.11

    steps: 
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
      
      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dbt/requirements.txt

      - name: Run dbt linting checks
        run: | 
          bash ./bin/dbt_linter.sh

  ci_python:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      # https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dbt/requirements.txt

      - name: Run pytest
        run: |
          bash ./bin/python_test.sh
